#lane_control/lane_controller_node

L: 0.35
th_seg_dist: 0.35
th_seg_count: 6
off_lane: 0.20
th_seg_close: 2
th_seg_far: 7
th_turn_slope: 3.0
th_lane_slope: 0.75
th_st_slope: 0.1
wt_slope: 200.0
wt_dist: 1
pow_slope: 8
pow_dist: 3
v: 0.2