#lane_control/lane_controller_node

L: 0.35
max_L: 1.0
th_seg_dist: 0.35
th_seg_count: 6
off_lane: 0.17
th_seg_close: 2
th_seg_far: 7
th_turn_slope: 1.5
th_lane_slope: 0.75
th_st_slope: 0.05   #0.1
wt_slope: 1
wt_slope_st: 2
wt_dist: 1
pow_slope: 8
pow_dist: 3
v: 0.5
wt_omega: 0.001
th_omega: 2.0
min_slope: 0.005
exp: 3.0